#!/bin/bash
set -eu

DOCKER_IMAGE_NAME=document-download-frontend
PORT=7001

API_HOST_NAME=${API_HOST_NAME:-"http://host.docker.internal:6011"}
DOCUMENT_DOWNLOAD_API_HOST_NAME=${DOCUMENT_DOWNLOAD_API_HOST_NAME:-"http://host.docker.internal:7000"}
DOCUMENT_DOWNLOAD_API_HOST_NAME_INTERNAL=${DOCUMENT_DOWNLOAD_API_HOST_NAME_INTERNAL:-"http://host.docker.internal:7000"}

docker run -it --rm \
  -e NOTIFY_ENVIRONMENT=$NOTIFY_ENVIRONMENT \
  -e FLASK_APP=$FLASK_APP \
  -e FLASK_DEBUG=$FLASK_DEBUG \
  -e API_HOST_NAME=$API_HOST_NAME \
  -e DOCUMENT_DOWNLOAD_API_HOST_NAME=$DOCUMENT_DOWNLOAD_API_HOST_NAME \
  -e DOCUMENT_DOWNLOAD_API_HOST_NAME_INTERNAL=$DOCUMENT_DOWNLOAD_API_HOST_NAME_INTERNAL \
  -e WERKZEUG_DEBUG_PIN=${WERKZEUG_DEBUG_PIN:-"off"} \
  -e PORT=${PORT} \
  -p 127.0.0.1:${PORT}:${PORT} \
  -v $(pwd):/home/vcap/app \
  ${DOCKER_IMAGE_NAME} \
  ${@}
